name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  NUGET_XMLDOC_MODE: skip
  WORKFLOW_BUILD_SLN: BigInteger.sln
  PACK_CSPROJ: BigInteger/BigInteger.csproj

permissions:
  contents: write

jobs:
  get-version:
    uses: kzrnm/dotnet-actions/.github/workflows/get-version.yml@v2
    with:
      project-path: BigInteger/BigInteger.csproj

  verify:
    needs: get-version
    uses: ./.github/workflows/reusable_verify.yml
    permissions:
      contents: read
      pages: write
      id-token: write

  build:
    runs-on: ubuntu-latest
    needs: get-version
    strategy:
      matrix:
        target:
          - version: ${{needs.get-version.outputs.version}}
            configuration: Release
          - version: ${{needs.get-version.outputs.version}}-embedded
            configuration: Debug
            property: -property:Embedding=true
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            7.0.x
      - uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/Directory.Build.props') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Build
        run: dotnet build ${{ env.WORKFLOW_BUILD_SLN }} -c ${{ matrix.target.configuration }} -p:Version=${{ matrix.target.version }} ${{ matrix.target.property }}
      - name: Test
        run: dotnet test ${{ env.WORKFLOW_BUILD_SLN }} --no-build --logger GitHubActions -c ${{ matrix.target.configuration }}
      - name: Pack
        run: dotnet pack ${{ env.PACK_CSPROJ }} --no-build -c ${{ matrix.target.configuration }} -o bin/Packages/${{ matrix.target.configuration }} -p:Version=${{ matrix.target.version }}
      - uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.target.configuration }}
          path: bin/Packages/${{ matrix.target.configuration }}
          retention-days: 1

  merge:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist-Debug
          path: Package
      - uses: actions/download-artifact@v4
        with:
          name: dist-Release
          path: Package
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: Package

  publish:
    needs: [get-version, verify, build]
    if: ${{ needs.get-version.outputs.is-new == 'true' }}
    uses: kzrnm/dotnet-actions/.github/workflows/publish.yml@v2
    with:
      artifact-name: dist
      version: ${{ needs.get-version.outputs.version }}
      is-prerelease: ${{ fromJson(needs.get-version.outputs.is-prerelease) }}
    secrets:
      NUGET_KEY: ${{ secrets.NUGET_KEY }}
